# Generated by Django 5.2.8 on 2025-11-18 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=10)),
            ],
            options={
                'db_table': '"inventory"."supplier"',
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasan.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasan.supplier')),
            ],
            options={
                'db_table': '"inventory"."supplier_product"',
            },
        ),
    ]
