# Generated by Django 5.2.8 on 2025-11-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasan', '0002_supplier_supplierproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familypackage',
            old_name='family_size',
            new_name='family_size_min',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='market_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_qty',
            new_name='net_quantity',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_images/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_pan_images/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pan_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
