# Generated by Django 5.2.8 on 2025-11-23 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': '"inventory"."brand"',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': '"inventory"."category"',
            },
        ),
        migrations.CreateModel(
            name='FamilyPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('family_size_min', models.IntegerField()),
                ('family_size_max', models.IntegerField()),
                ('base_price', models.FloatField()),
            ],
            options={
                'db_table': '"inventory"."family_package"',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='supplier_images/')),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_image', models.ImageField(blank=True, null=True, upload_to='supplier_pan_images/')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': '"inventory"."supplier"',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('market_price', models.FloatField()),
                ('net_quantity', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasan.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasan.category')),
            ],
            options={
                'db_table': '"inventory"."product"',
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasan.familypackage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasan.product')),
            ],
            options={
                'db_table': '"inventory"."package_item"',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasan.category')),
            ],
            options={
                'db_table': '"inventory"."sub_category"',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasan.subcategory'),
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasan.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rasan.supplier')),
            ],
            options={
                'db_table': '"inventory"."supplier_product"',
            },
        ),
    ]
