# Generated by Django 5.2.8 on 2025-11-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderitem_price_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyrasantemplate',
            name='user',
        ),
        migrations.DeleteModel(
            name='MonthlyRasanItem',
        ),
        migrations.DeleteModel(
            name='MonthlyRasanTemplate',
        ),
    ]
